In [1]:
import pandas as pd
import json
from pandas.io.json import json_normalize
import glob

In [5]:
fnames = glob.glob('yelp_dataset_challenge_academic_dataset/yelp*.json')
fnames

['yelp_dataset_challenge_academic_dataset/yelp_academic_dataset_review.json',
 'yelp_dataset_challenge_academic_dataset/yelp_academic_dataset_business.json',
 'yelp_dataset_challenge_academic_dataset/yelp_academic_dataset_user.json',
 'yelp_dataset_challenge_academic_dataset/yelp_academic_dataset_checkin.json',
 'yelp_dataset_challenge_academic_dataset/yelp_academic_dataset_tip.json']

In [3]:
# read in data set
def read_data(fname):
    data = []
    with open(fname) as f:
        for line in f:
            data.append(json.loads(line))

    df = pd.DataFrame(data)
    return df

In [4]:
# use recursion to find nested data

# find nested data
def find_dictionary(df):
    return df.columns[df.apply(lambda x: isinstance(x[0], dict))]

# create dataframe from nested data
def create_df_col(df, col):
    pass

In [5]:
df = read_data(fnames[2])

In [19]:
col = find_dictionary(df)
comp = json_normalize(list(df.compliments))
vote = json_normalize(list(df.votes))

In [23]:
comp.join(vote, rsuffix='vote')

,cool,cute,funny,hot,list,more,note,photos,plain,profile,writer,coolvote,funnyvote,useful
0,78,15,11,48,NaN,3,20,15,25,8,9,245,166,278
1,1521,209,561,1032,37,129,589,287,921,110,290,9837,6849,12642
2,145,23,122,102,4,19,82,23,86,9,24,727,907,1445
3,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5,1,11
4,1,2,NaN,1,NaN,1,1,NaN,2,NaN,2,11,10,34
5,3420,274,1462,2599,89,218,1009,1854,3902,220,1229,16174,12453,16940
6,3,1,1,1,5,NaN,1,4,4,1,2,43,35,86
7,14,4,2,8,1,1,5,NaN,6,2,1,25,39,38
8,1,NaN,NaN,1,NaN,NaN,NaN,NaN,5,NaN,NaN,30,25,118
9,3,1,8,5,NaN,2,3,1,5,1,2,39,40,207
10,3,NaN,NaN,1,NaN,NaN,NaN,1,2,NaN,NaN,15,6,28
11,211,82,70,265,3,16,85,57,102,10,18,1914,1105,2381
12,1,2,NaN,NaN,NaN,1,1,NaN,1,NaN,1,18,42,43
13,1,NaN,NaN,NaN,NaN,1,2,NaN,3,1,3,22,45,179
14,58,2,15,24,1,3,11,1,60,2,19,424,331,521
15,8,1,1,3,NaN,NaN,4,NaN,6,NaN,3,68,58,229
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0,26
17,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,6,0,11
18,1,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,1,0,5
19,2,NaN,NaN,1,NaN,1,1,NaN,1,NaN,NaN,11,6,39
20,16,2,4,27,1,4,17,3,10,1,23,165,112,223
21,2,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,15,16,46
22,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,0,0,2
23,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,3,NaN,1,12,4,13
24,NaN,1,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,2,1,2
25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,7
26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,2,0
27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,2,7
28,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,5,8,21
29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
366685,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1,NaN,NaN,1,2,18
366686,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,2
366687,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,2
366688,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,3,2,6
366689,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,1,2
366690,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1,3
366691,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,3,8,10
366692,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,28,52
366693,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,1
366694,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0,3
366695,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0
366696,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,1,4
366697,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,2
366698,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7,6,13
366699,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,1,6
366700,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0
366701,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,2,0
366702,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,3
366703,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0
366704,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0
366705,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0
366706,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0
366707,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,5
366708,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0
366709,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0,3
366710,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,1
366711,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4,NaN,NaN,1,0,3
366712,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0
366713,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,2
366714,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0

In [ ]:
# save to sqlite